feat: replace git based topology ingestion by JSON Merge Patch
traefik/hub-agent-traefik pull request #9
Opened 2022-07-20 13:49 UTC by youkoulayley

This PR replaces the current topology ingestion mechanism which is based on pushing git commits by a custom solution using JSON Merge Patch [RFC-7386](https://datatracker.ietf.org/doc/html/rfc7386)

This new solution reduces the amount of a data transfer thanks to the JSON Merge Patch thin format and gzip compression. We've measured a ~10x reduction in data volume transferred. This change will also ease infrastructure operations.

The only information we are collecting are the Services, with the following fields:
- name
- ports
- container name / networks

These services are used on the platform for providing the UI which display the service the user can expose.

Notable changes:
- Stop sending topology data we don't need anymore
- Replace topology.Store by a JSON Merge Patch mechanism 

Co-authored-by: Harold Ozouf <harold.ozouf@traefik.io>

2022-07-22 14:30 UTC, LandryBe approved these changes
LGTM

2022-07-25 15:16 UTC, juliens requested changes

2022-07-25 15:16 UTC, juliens commented on pkg/topology/cluster.go
>  	Ports     []int      `json:"externalPorts,omitempty"`
Maybe we can you rename Ports to ExternalPorts?

2022-08-01 14:16 UTC, juliens approved these changes
LGTM

2022-08-03 14:04 UTC, merged